### ISSUE TITLE
Tiffslide fails in multi-threaded mode

### ISSUE THREAD

**Issue by lukasii** [bayer-science-for-a-better-life/tiffslide#14]
Hi and thanks for this promising library. 

My group has started using it as an openslide replacement and we just encountered one serious issue. Extracting patches from large tiff images is the most efficient when using multi-threading. Unfortunately, tiffslide fails in this mode. Tested using two independent Linux environments and the most recent versions (as of Dec 13) of both tiffslide and tifffile, along with python 3.8 and 3.9. Attached is a minimalistic example using python's multi-threading support. Before running just edit the file and point it to some tiff file (`tiff_file` variable).

Details/notes:

- the attached script will work fine when `num_threads = 1` 
- with `num_threads = 2` it will work most of the time and crash occasionally (reporting image problems/corruption).
- with a higher thread count (8 and up) it will crash constantly. This kind of behaviour is typical for programs which suffer from threading issues.
- when switching to openslide (`import openslide`), the attached script works fine (and  fast) even for over 30 threads.
- it is not certain which exact library is to blame here (tifffile or tiffslide), so maybe you will be able to pinpoint that.

Thanks for looking into this. If you need more details I'll be glad to provide them.

Attachment: 
[tiffslide-bug.zip](https://github.com/bayer-science-for-a-better-life/tiffslide/files/7707420/tiffslide-bug.zip)

**Comment by ap--** [comment]
This has now been fixed in `v0.3.0` a new release will be out very soon.

Cheers,
Andreas 😃

**Comment by lukasii** [comment]
Unfortunately, tiffslide fails again in parallel mode, this time using pytorch dataloaders. This is a very common technique used in WSI processing with pytorch, the only difference is that it uses process based parallelisation (rather than threads, as in the original bug report).

The symptoms are exactly the same:

- using tiffslide and one dataloader process (`num_workers=1`) everything works fine
- using tiffslide and more dataloader processes (e.g. `num_workers=4`) the processing fails
- using openslide everything works fine regardless of the `num_workers` value

Tested using tiffslide version 1.0.0 and tifffile version 2022.2.9. Please see the attached minimalist example.

[tiffslide-bug2.zip](https://github.com/bayer-science-for-a-better-life/tiffslide/files/8112916/tiffslide-bug2.zip)
