### ISSUE TITLE
How to cite?

### ISSUE THREAD

**Issue by sarthakpati** [bayer-science-for-a-better-life/tiffslide#17]
Hi,

How do we cite this repo in publications? 😄 

Ideally, it would be great if there was a journal publication (e.g., JOSS), but even a Zenodo-generated DOI would suffice.

Cheers,
Sarthak

**Comment by sdvillal** [comment]
We do plan to try to publish this together with other digital pathology tools we are developing, but it will take a while .

@ap-- should we quickly cut v1.0 and publish in zenodo? That would work well with our other short-term data release plans

**Comment by ap--** [comment]
It's on the list 👍 
I'll update this issue when things move forward.

**Comment by ap--** [comment]
Okay, we're on Zenodo now 🎉
