### ISSUE TITLE
Allowing tile to extend beyond image region by padding.

### ISSUE THREAD

**Issue by BenjaminIsaac0111** [bayer-science-for-a-better-life/tiffslide#27]
Hello, 

I have a use case where I use point annotated tumour regions to extract patches to train a segmentation deep learning system.

Each patch is a constant size, but depending on the coordinate location of the point annotation on the slide, this means that occasionally, a patch extends beyond the image itself by some margin if that point is close to the edge of an image.

In short, will there be an option to pad the tile? 

When using openslide, any region outside the image is given a black RGB value by default.

For now, I am catching the error but the flexibility to do this with padding might be important for some. And perhaps even return a mask where this padding happens?

Thanks,
Wilson

**Comment by ap--** [comment]
Hey there,

Thanks for the bug report! ❤️ 
I'm a bit hesitant to implement this, but openslide definitely allows you to pad in all directions 🤔  ...

```python
import numpy as np
import openslide

def _is_padding(im):
    return np.all(np.array(im) == 0)

slide = openslide.open_slide("some.svs")
slide.level_dimensions
>>> ((63743, 36055), (15935, 9013), (3983, 2253))

# oob positive
_is_padding(slide.read_region((1_000_000, 1_000_0000), 0, (10, 10)))
>>> True

# oob negative
_is_padding(slide.read_region((-1_000_000, -1_000_0000), 0, (10, 10)))
>>> True

# oob higher level than available
_is_padding(slide.read_region((0, 0), 1000, (10, 10)))
>>> True

# oob negative level
_is_padding(slide.read_region((0, 0), -1000, (10, 10)))
>>> True

# empty reads
slide.read_region((0, 0), 0, (0, 0))  # tile width and/or height can be 0
>>> <PIL.Image.Image image mode=RGBA size=0x0 at 0x7F926D19E220>

```

I think I'd like to default to not allow this (because I think it's a potential source of unwanted bugs). But we could offer a keyword argument and in addition some global setting to be able to allow the exact behavior above. Maybe even allowing to set the padding value.

This should also ship with more compatibility test for openslide as mentioned in #1. 


Would you like to contribute to implementing this functionality in a PR?
I could provide some feedback, or sketch out an initial draft.

Cheers,
Andreas 😃

**Comment by One-sixth** [comment]
@ap-- 
I had this problem recently too.
We need to keep the same padding method as openslide.
The coordinate system I use here uses negative numbers and functions that allow to exceed boundaries.

This makes it easy to slice the slide without running into annoying border issues.
In practice, we always do padding to keep the model input size.
Resize will causes abnormal image aspect ratio.

**Comment by ap--** [comment]
Hey everyone,

It does make sense to support this.

The implementation would be limited to these few lines:
https://github.com/bayer-science-for-a-better-life/tiffslide/blob/56b5bbda36a2792a93b3eabd30c590f004835b41/tiffslide/tiffslide.py#L358-L408

TODOs:
- [ ] add keyword only `padding` argument defaulting to `True`
- [ ] calculate padding needed in the two width and height directions with least overhead possible
- [ ] emit warning if region is entirely out of bounds, i.e. `read_region((-100, -100), 0, (50, 50))`
- [ ] add a single call to `np.pad` just between here (Line 404), guarded only if needed: https://github.com/bayer-science-for-a-better-life/tiffslide/blob/56b5bbda36a2792a93b3eabd30c590f004835b41/tiffslide/tiffslide.py#L402-L405
- [ ] add tests for the specific edge-cases


This is a pretty well defined PR. Anyone up for tackling it? 😃 

Cheers,
Andreas

**Comment by One-sixth** [comment]
> Hey everyone,
> 
> It does make sense to support this.
> 
> The implementation would be limited to these few lines:
> 
> https://github.com/bayer-science-for-a-better-life/tiffslide/blob/56b5bbda36a2792a93b3eabd30c590f004835b41/tiffslide/tiffslide.py#L358-L408
> 
> TODOs:
> 
> * [ ]  add keyword only `padding` argument defaulting to `True`
> * [ ]  calculate padding needed in the two width and height directions with least overhead possible
> * [ ]  emit warning if region is entirely out of bounds, i.e. `read_region((-100, -100), 0, (50, 50))`
> * [ ]  add a single call to `np.pad` just between here (Line 404), guarded only if needed: https://github.com/bayer-science-for-a-better-life/tiffslide/blob/56b5bbda36a2792a93b3eabd30c590f004835b41/tiffslide/tiffslide.py#L402-L405
> * [ ]  add tests for the specific edge-cases
> 
> This is a pretty well defined PR. Anyone up for tackling it? 😃
> 
> Cheers, Andreas

I am working on it.
A PR will open later.

**Comment by ap--** [comment]
Let's start with padding with 0 only.
We'll think about user provided padding values in a separate issue.

Thank you so much for contributing!

**Comment by BenjaminIsaac0111** [comment]
Amazing, just saw this! 

Thanks for the implementation! @ap-- @One-sixth 

Wilson
