### ISSUE TITLE
overflow encountered in long_scalars   ry0 = (base_y * level_h) // base_h

### ISSUE THREAD

**Issue by One-sixth** [bayer-science-for-a-better-life/tiffslide#29]
Overflow issues may occur when the user enters a parameter of type np.int32. As a result, some images cannot be displayed.
This can be tricky to spot because there's only an obscure warning, we'd better cast the parameter to int explicitly.
Openslide does not have this problem.

The problem arises in
````
         rx0 = (base_x * level_w) // base_w
         ry0 = (base_y * level_h) // base_h
````
```
d:\github_repo\tiffslide\tiffslide\tiffslide.py:414: RuntimeWarning: overflow encountered in long_scalars
  ry0 = (base_y * level_h) // base_h
```

In my tiffslide library that fixes the padding problem.
Thumbnails are generated from the level_0, level 0 size (39840, 50329).

location, size is np.int32
![o2](https://user-images.githubusercontent.com/23693633/161369279-d3ee1f9d-45b4-45d0-a0f9-ca64b6bf1d9e.jpg)

location, size is int
![o3](https://user-images.githubusercontent.com/23693633/161369711-fb35072c-328a-4d23-8f3a-f27e31b41f89.jpg)

**Comment by ap--** [comment]
I think I fixed this. Can you verify?
I couldn't really reproduce the RuntimeWarning from numpy

**Comment by One-sixth** [comment]
@ap--
Great! The RuntimeWarning no longer appears.

**Comment by ap--** [comment]
Nice. I'll make a new release soon then.

One quick question out of interest: Are you running this on a 32bit Windows?

**Comment by One-sixth** [comment]
> Nice. I'll make a new release soon then.
> 
> One quick question out of interest: Are you running this on a 32bit Windows?

My system is win11 x64, python3.9 and numpy 1.22.3. And I usually wrap my coordinates with np.int32 .

**Comment by ap--** [comment]
Interesting.

So the reason I can't reproduce this, is because on my machine the runtime warning for numpy scalars will only be raised if two numpy scalars get multiplied with each other.

```python
In [1]: import numpy as np

In [2]: x = np.uint8(100)

In [3]: x * 100
Out[3]: 10000

In [4]: x * x
<ipython-input-4-0dcf3a591295>:1: RuntimeWarning: overflow encountered in ubyte_scalars
  x * x
Out[4]: 16

In [5]: x * 100 // x
Out[5]: 100

In [6]: type(np.zeros((3,3,3)).shape[0])
Out[6]: int
```

And for me in this code block:
```python
         rx0 = (base_x * level_w) // base_w
         ry0 = (base_y * level_h) // base_h
```

`level_w` and `level_h` come from `np.ndarray.shape` which are of type `int`, and therefore multiplying np.int32 with int in your case would upcast automatically. I wonder if there's a difference between windows and linux in this case...

But anyways, I'm happy that it works for you now :smiley:

**Comment by One-sixth** [comment]
@ap-- 
There is indeed a difference.
```
# linux
o = np.int32(60000) * 60000
# o: np.int64 = 3600000000
#windows
o = np.int32(60000) * 60000
# <ipython-input-6-59000faa3d3d>:1: RuntimeWarning: overflow encountered in long_scalars
# o: np.int32 = -694967296
```
It seems to be an ambiguity issue with numpy on different platforms.

**Comment by ap--** [comment]
Okay. Then all of this makes of course sense.
I guess it's just another thing one has to keep in mind when developing cross-platform numpy code :shrug: 

I'll add a test for ensuring that we don't run into this RuntimeWarning on any platform.

Thanks again for investigating and your help with the implementation :smiley: 

Cheers,
Andreas
