### ISSUE TITLE
[Bug] Padding is expected. But it is not padding.

### ISSUE THREAD

**Issue by One-sixth** [bayer-science-for-a-better-life/tiffslide#38]
Hello. I found a bug.

The bug here. https://github.com/bayer-science-for-a-better-life/tiffslide/blob/main/tiffslide/tiffslide.py#L421

The comparison should be level_h and level_w. Not base_h and base_w .

Just replace .
from
```
        in_bound = 0 <= rx0 and rx1 <= base_w and 0 <= ry0 and ry1 <= base_h
```
to
```
        in_bound = 0 <= rx0 and rx1 <= level_w and 0 <= ry0 and ry1 <= level_h
```
Then the bug is fixed.

**Comment by ap--** [comment]
Thank you so much for the fix @One-sixth !

Cheers,
Andreas 😃
