### ISSUE TITLE
Support for axes=='YX' and uint16 svs files.

### ISSUE THREAD

**Issue by One-sixth** [bayer-science-for-a-better-life/tiffslide#46]
Hello. I have some svs files whose axes are 'YX' and dtype is uint16.
Openslide doesn't support opening them, but tiffslide can open them with a little modification.

I opened a PR.

**Comment by ap--** [comment]
Interesting. Would it be possible to share one of those svs files for tests?

**Comment by One-sixth** [comment]
@ap-- 
The original svs file I can't share. I generated an svs image with the same format. 'YX' and uint16. It can also help with troubleshooting.
[a9.zip](https://github.com/bayer-science-for-a-better-life/tiffslide/files/9574821/a9.zip)

**Comment by ap--** [comment]
Hi @One-sixth 

Thanks for sharing the generated test file :heart:

Would it be possible to share the output of `tiffinfo` of an original file? What I'm specifically interested in is the original Aperio `ImageDescription` and the original image format. (feel free to mask out certain information if you consider it confidential)

**Comment by One-sixth** [comment]
@ap-- 
Here is the output of a raw svs file. (Some user information and time have been masked)
[info.txt](https://github.com/bayer-science-for-a-better-life/tiffslide/files/9582336/info.txt)

**Comment by ap--** [comment]
Closed via #47
